#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    environment:
      JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

    working_directory: ~/zmi-nerd

    steps:
      - checkout
      - run: yarn
      - run: yarn compile
      - run: yarn test --forceExit --detectOpenHandles
      - run: bash <(curl -s https://codecov.io/bash)
