#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0-browsers

    environment:
      JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

    working_directory: ~/vitx

    steps:
      - checkout
      - run: yarn
      - run: yarn test --runInBand --detectOpenHandles
      - run: bash <(curl -s https://codecov.io/bash)
